AWSTemplateFormatVersion : 2010-09-09
Resources:
  S3TransactionsBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: storitransactionsbucket
      NotificationConfiguration:
        LambdaConfigurations:
          - Event: s3:ObjectCreated:*
            Function: !GetAtt LambdaFunction.Arn
            Filter:
              S3Key:
                Rules:
                - Name: suffix
                  Value: .csv

Outputs:
  S3TransactionsBucket:
    Value: !Ref S3TransactionsBucket
    Export:
      Name: S3TransactionsBucket